id = "harper"
name = "harper"
version = "0.0.4"
schema_version = 1
authors = ["Stef Robbe <stef.robbe@protonmail.com>"]
description = "Harper LS support"
repository = "https://github.com/stef16robbe/harper_zed"

[language_servers.harper-ls]
name = "Harper LS"
# Not all of these are supported by Harper yet, see: https://github.com/Stef16Robbe/harper_zed/pull/4#issuecomment-2469318095
# See nvim config for supported langs: https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs/harper_ls.lua
languages = [
    # General Purpose
    "Python",
    "Go",
    "C",
    "Cpp",
    "Java",
    "Rust",
    "Zig",
    "Dart",
    "Elixir",
    "Erlang",
    "Gleam",
    "Groovy",
    "Haskell",
    "Julia",
    "Kotlin",
    "Nim",
    "OCaml",
    "PHP",
    "PureScript",
    "R",
    "Racket",
    "Roc",
    "Ruby",
    "Scala",
    "Scheme",
    "Uiua",

    # Scripting
    "Lua",
    "Luau",
    "Bash",
    "Deno",
    "Fish",
    "GDScript",
    "Rego",

    # Web
    "HTML",
    "CSS",
    "Javascript",
    "Typescript",
    "Svelte",
    "Astro",
    "Vue",
    "Elm",

    # Markup
    "Markdown",
    "AsciiDoc",
    "ReStructuredText",
    "XML",
    "Typst",
    "LaTeX",

    # Data serialization
    "TOML",
    "JSON",
    "Jsonnet",
    "YAML",

    # Compiled
    "Swift",
    "CSharp",

    # Configuration / Automation
    "Ansible",
    "Docker",
    "Makefile",
    "Terraform",
    "Yarn",

    # Other
    "Biome",
    "Clojure",
    "Emmet",
    "GLSL",
    "Prisma",
    "Proto",
    "Solidity",

    # Not supported yet
    # "typescriptreact",
    # "gitcommit",
]
