id = "harper"
name = "harper"
version = "0.0.3"
schema_version = 1
authors = ["Stef Robbe <stef.robbe@protonmail.com>"]
description = "Harper LS support"
repository = "https://github.com/stef16robbe/harper_zed"

[language_servers.harper-ls]
name = "Harper LS"
languages = [
    "Markdown",
    "Rust",
    "Typescript",
    # "typescriptreact", not supported yet in Zed
    "Javascript",
    "Python",
    "Go",
    "C",
    "Cpp",
    "Ruby",
    "Swift",
    "CSharp",
    "TOML",
    "Lua",
    # "gitcommit", not supported yet in Zed
    "Java",
    "HTML",
]
